### ISSUE TITLE
Error doing job: Future exception was never retrieved

### ISSUE THREAD

**Issue by Nurgus** [MorneSaunders360/Solar-Sunsynk#1]
Not available in HACS, I had to add it as a custom hacs repository. 

I have no synsynk sensors and my home assistant log is filled with this repeating error:

```
2023-05-10 10:02:35.502 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/solar_sunsynk/__init__.py", line 112, in update_states
    token = responseAuth["data"]["access_token"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by MorneSaunders360** [comment]
My apologies meant to say that you need to add it to the custom Hacs repository, will update my readme. The bug has been fixed and a update is available.
